### ISSUE TITLE
build error : /Users/takabatomoki/Desktop/esp_oled/HelloWorld/main/main.c:47: undefined reference to `SSD1306_SPIMasterInitDefault'

### ISSUE THREAD

**Issue by acsses** [TaraHoleInIt/tarablessd1306_examples#3]
I built this program but got the following error
` /Users/<user name>/Desktop/esp_oled/HelloWorld/main/main.c:47: undefined reference to SSD1306_SPIMasterInitDefault'`
How do I resolve this error?
I would be grateful if you could teach

**Comment by TaraHoleInIt** [comment]
make menuconfig
component config->tarable ssd1306->enable default spi interface

**Comment by acsses** [comment]
Thank you!!
Tried and successfully built!!
We apologize for the inconvenience.
Thank you very much!!!!!
